import json
import os
import logging
from typing import Dict, List, Optional, Any, TypedDict
import asyncpg
from pydantic import BaseModel, Field
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI

logger = logging.getLogger(__name__)

# ============================================================================
# 1. STATE DEFINITION & PYDANTIC OUTPUT SCHEMAS
# ============================================================================

class DynamicRationale(BaseModel):
    why_now: str = Field(description="Clear reason why this node is placed at this point in the path.")
    skill_gap_addressed: str = Field(description="The specific skill gap or prerequisite targeted.")

class DynamicRoadmapStep(BaseModel):
    node_id: str = Field(description="Unique ID for the step, e.g., 'rm_react_hooks' or 'remedial_state_mgmt'")
    title: str = Field(description="Display title of the learning node.")
    type: str = Field(description="Node type: 'skill', 'course', 'project', or 'assessment'")
    target_skill_id: str = Field(description="Associated skill slug from database catalog.")
    difficulty: str = Field(description="Beginner, Intermediate, or Advanced")
    estimated_hours: int = Field(description="Estimated hours to complete.")
    action_type: str = Field(description="'retained', 'injected_remedial', 'fast_tracked_skip', or 'added'")
    rationale: DynamicRationale

class StructuredReplanOutput(BaseModel):
    headline: str = Field(description="Short summary message for the UI (e.g., 'Path updated to reinforce State Management').")
    reasoning: str = Field(description="Detailed narrative explaining how the path adapted to user performance.")
    updated_steps: List[DynamicRoadmapStep]

class AdaptiveGraphState(TypedDict):
    pool: asyncpg.Pool
    learner_id: str
    target_career_id: str
    assessment_signal: Dict[str, Any]  # {step_id, target_skill_id, score_percentage, user_feedback}
    current_skills: Dict[str, float]   # {skill_id: proficiency_score (0.0 - 1.0)}
    career_requirements: Dict[str, int] # {skill_id: required_score (0 - 100)}
    skill_gaps: List[Dict[str, Any]]
    current_roadmap_nodes: List[Dict[str, Any]]
    
    # Outputs generated by workflow
    new_mastery_score: Optional[float]
    replan_output: Optional[Dict[str, Any]]
    replan_status_message: str

# ============================================================================
# 2. WORKFLOW NODES
# ============================================================================

def bayesian_knowledge_estimator_node(state: AdaptiveGraphState) -> Dict[str, Any]:
    """
    Step 1: Runs Bayesian Knowledge Tracing (BKT) to update skill mastery probability P(L_t).
    """
    signal = state.get("assessment_signal", {})
    target_skill_id = signal.get("target_skill_id")
    score_pct = signal.get("score_percentage", 0.0)
    skills = dict(state.get("current_skills", {}))
    
    if not target_skill_id:
        return {"current_skills": skills, "new_mastery_score": None}

    # Retrieve prior probability P(L_t-1)
    prior_mastery = skills.get(target_skill_id, 0.20)

    # BKT Model Constants
    slip_rate = 0.10     # P(Fail | Mastered)
    guess_rate = 0.20    # P(Pass | Not Mastered)
    transit_rate = 0.15  # Learning transition probability P(T)

    is_passed = score_pct >= 65.0

    if is_passed:
        numerator = prior_mastery * (1.0 - slip_rate)
        denominator = numerator + ((1.0 - prior_mastery) * guess_rate)
    else:
        numerator = prior_mastery * slip_rate
        denominator = numerator + ((1.0 - prior_mastery) * (1.0 - guess_rate))

    posterior_mastery = numerator / max(denominator, 1e-6)

    # Transition update step: P(L_t) = P(L_t | Obs) + (1 - P(L_t | Obs)) * P(T)
    updated_mastery = posterior_mastery + ((1.0 - posterior_mastery) * transit_rate)
    final_score = round(max(0.0, min(1.0, updated_mastery)), 4)
    
    skills[target_skill_id] = final_score
    
    return {
        "current_skills": skills,
        "new_mastery_score": final_score
    }


async def graph_context_retriever_node(state: AdaptiveGraphState) -> Dict[str, Any]:
    """
    Step 2: Queries Supabase for career target skill requirements and computes skill gaps.
    """
    pool = state["pool"]
    learner_id = state["learner_id"]
    career_id = state["target_career_id"]
    current_skills = state["current_skills"]

    # Load required career skills from relational database
    async with pool.acquire() as conn:
        career_skills = await conn.fetch(
            "SELECT skill_id, required_score, importance FROM career_skills WHERE career_id = $1",
            career_id
        )
        
        roadmap_nodes = await conn.fetch(
            """
            SELECT rn.id, rn.title, rn.type, rn.skill_id, rn.difficulty, rn.duration_text, lrn.status
            FROM roadmap_nodes rn
            LEFT JOIN learner_roadmap_nodes lrn ON rn.id = lrn.node_id AND lrn.learner_id = $1
            WHERE rn.career_id = $2
            ORDER BY rn.stage ASC
            """,
            learner_id, career_id
        )

    career_req_map = {r["skill_id"]: r["required_score"] for r in career_skills}
    
    # Calculate explicit gaps: gap = required - (current_proficiency * 100)
    skill_gaps = []
    for skill_id, req_score in career_req_map.items():
        curr_prof = int(current_skills.get(skill_id, 0.0) * 100)
        gap = max(0, req_score - curr_prof)
        if gap > 0:
            skill_gaps.append({
                "skill_id": skill_id,
                "required_score": req_score,
                "current_score": curr_prof,
                "gap": gap
            })

    return {
        "career_requirements": career_req_map,
        "skill_gaps": skill_gaps,
        "current_roadmap_nodes": [dict(r) for r in roadmap_nodes]
    }


async def llm_dynamic_replanner_node(state: AdaptiveGraphState) -> Dict[str, Any]:
    """
    Step 3: Calls LLM to dynamically restructure the path, prune completed steps, and insert remedial nodes.
    """
    # Inside llm_dynamic_replanner_node:
    llm = ChatOpenAI(
        base_url="https://api.cerebras.ai/v1",
        model="gemma-4-31b", 
        temperature=0.2,
        api_key=os.environ.get("CEREBRAS_API_KEY") 
    )
    structured_llm = llm.with_structured_output(StructuredReplanOutput)

    signal = state.get("assessment_signal", {})
    score_pct = signal.get("score_percentage", 100.0)
    target_skill = signal.get("target_skill_id", "Unknown")

    prompt = f"""
    You are an AI Adaptive Curriculum Engine.
    
    Context:
    - Learner ID: {state['learner_id']}
    - Target Career ID: {state['target_career_id']}
    - Latest Assessment Signal: Skill='{target_skill}', Score={score_pct}%, Feedback='{signal.get("user_feedback", "None")}'
    - Current Skill Gaps: {json.dumps(state['skill_gaps'])}
    - Active Roadmap Nodes: {json.dumps(state['current_roadmap_nodes'])}
    
    Re-planning Logic Guidelines:
    1. IF Score < 60%: Inject a 'remedial' node at the beginning of the sequence targeting '{target_skill}'. Action type: 'injected_remedial'.
    2. IF Score >= 90%: Fast-track the learner by pruning redundant beginner steps for '{target_skill}'. Action type: 'fast_tracked_skip'.
    3. FOR OTHER STEPS: Keep them sequenced logically by stage and assign 'retained' or 'added'.
    4. Provide clear rationales for why each node is sequenced where it is.
    """

    response: StructuredReplanOutput = await structured_llm.ainvoke(prompt)
    
    return {
        "replan_output": response.model_dump(),
        "replan_status_message": response.headline
    }


async def database_persister_node(state: AdaptiveGraphState) -> Dict[str, Any]:
    """
    Step 4: Persists updated skills, updated node sequences, and replan logs back to PostgreSQL.
    """
    pool = state["pool"]
    learner_id = state["learner_id"]
    current_skills = state["current_skills"]
    replan_data = state["replan_output"]
    signal = state.get("assessment_signal", {})

    if not replan_data:
        return {}

    async with pool.acquire() as conn:
        async with conn.transaction():
            # 1. Update learner_skills table with new BKT proficiency scores
            for skill_id, mastery in current_skills.items():
                score_0_100 = int(mastery * 100)
                await conn.execute(
                    """
                    INSERT INTO learner_skills (learner_id, skill_id, proficiency_score, updated_at)
                    VALUES ($1, $2, $3, NOW())
                    ON CONFLICT (learner_id, skill_id)
                    DO UPDATE SET proficiency_score = EXCLUDED.proficiency_score, updated_at = NOW()
                    """,
                    learner_id, skill_id, score_0_100
                )

            # 2. Write to roadmap_replans table for history auditing
            step_ids = [s["node_id"] for s in replan_data["updated_steps"]]
            changes_json = json.dumps([{
                "node_id": s["node_id"],
                "action": s["action_type"],
                "why": s["rationale"]["why_now"]
            } for s in replan_data["updated_steps"]])

            await conn.execute(
                """
                INSERT INTO roadmap_replans (
                    learner_id, triggered_by_assessment_id, headline, reason, changes, updated_path
                )
                VALUES ($1, $2, $3, $4, $5::jsonb, $6)
                """,
                learner_id,
                signal.get("assessment_id"),
                replan_data["headline"],
                replan_data["reasoning"],
                changes_json,
                step_ids
            )

    return {}

# ============================================================================
# 3. GRAPH COMPILATION & EXECUTION ENTRY POINT
# ============================================================================

def build_adaptive_engine_graph():
    """
    Compiles the LangGraph state machine.
    """
    workflow = StateGraph(AdaptiveGraphState)

    workflow.add_node("bkt_estimator", bayesian_knowledge_estimator_node)
    workflow.add_node("context_retriever", graph_context_retriever_node)
    workflow.add_node("llm_replanner", llm_dynamic_replanner_node)
    workflow.add_node("db_persister", database_persister_node)

    workflow.set_entry_point("bkt_estimator")
    workflow.add_edge("bkt_estimator", "context_retriever")
    workflow.add_edge("context_retriever", "llm_replanner")
    workflow.add_edge("llm_replanner", "db_persister")
    workflow.add_edge("db_persister", END)

    return workflow.compile()

# Global compiled engine graph instance
adaptive_graph_app = build_adaptive_engine_graph()